---

# Fail2ban settings
# Ignore attempts from guacamole VM to prevent locking users out
fail2ban_ignoreips:
  - "{{ guacamole_private_ip }}"

# SSH server settings
ssh_allow_users: "{{ dsvm_admin_user }}"
ssh_server_match_address:
  - address: "{{ guacamole_private_ip }}"
    rules:
      - AllowUsers *
      - DenyUsers "{{ dsvm_admin_user }}"
      - PasswordAuthentication yes
      - AuthenticationMethods password

# SSH client settings
ssh_remote_hosts:
  - names: ["gpu"]
    options:
      - IdentityFile ~/.ssh/gpu_rsa

# Apt packages
apt_packages: "{{ apt_packages_development | union(apt_packages_shells) | union(apt_packages_editors) | union(apt_packages_latex) | union(apt_packages_extra) }}"

# Snap packages
snap_packages_default:
  - name: codium
    classic: yes
  - name: atom
    classic: yes
  - name: sublime-text
    classic: yes
  - name: pycharm-community
    classic: yes
  - name: gitkraken
    classic: yes
  - name: dbeaver-ce

snap_packages: "{{ snap_packages_default | union(snap_packages_extra) }}"
