#cloud-config
package_upgrade: false

write_files:
  - path: "/startwm.sh"
    content: |
      #!/bin/sh
      if [ -r /etc/default/locale ]; then
        . /etc/default/locale
        export LANG LANGUAGE
      fi
      # Start xfce4
      startxfce4
  - path: "/ldap.conf"
    content: |
      # The distinguished name of the search base.
      base LDAP_BASE_DN

      # Restrict users to those in the securioty group of this DSG
      filter LDAP_FILTER

      # Another way to specify your LDAP server is to provide an
      uri ldap://AD_DC_NAME_LOWER.DOMAIN_LOWER:389

      # The LDAP version to use (defaults to 3
      # if supported by client library)
      ldap_version 3

      # The distinguished name to bind to the server with
      # if the effective user ID is root. Password is
      # stored in /etc/ldap.secret (mode 600)
      rootbinddn LDAP_BIND_DN

      # Do not hash the password at all; presume
      # the directory server will do it, if
      # necessary. This is the default.
      pam_password md5
  - path: "/krb5.conf"
    content: |
      [libdefaults]
        default_realm = DOMAIN_UPPER

      # The following krb5.conf variables are only for MIT Kerberos.
        krb4_config = /etc/krb.conf
        krb4_realms = /etc/krb.realms
        kdc_timesync = 1
        ccache_type = 4
        forwardable = true
        proxiable = true

      # The following libdefaults parameters are only for Heimdal Kerberos.
        v4_instance_resolve = false
        v4_name_convert = {
          host = {
            rcmd = host
            ftp = ftp
          }
          plain = {
            something = something-else
          }
        }
        fcc-mit-ticketflags = true

      [realms]
          DOMAIN_UPPER = {
              kdc = AD_DC_NAME_UPPER.DOMAIN_UPPER:88
              admin_server = AD_DC_NAME_UPPER.DOMAIN_UPPER
              default_domain = DOMAIN_UPPER
              }

      [domain_realm]
            .DOMAIN_LOWER = DOMAIN_UPPER
            DOMAIN_LOWER = DOMAIN_UPPER

      [login]
        krb4_convert = true
        krb4_get_tickets = false
  - path: "/active_directory_step01_pre"
    content: |
      #!/bin/sh
      # Set up Active Directory
      # -----------------------
      echo "Setting up Active Directory..."
      # Ensure that sssd is running
      echo "Ensuring that sssd is running"
      systemctl status sssd.service
      # Add information to hosts file
      echo "Setting hostname"
      echo "MACHINENAME" > /etc/hostname
      cat /etc/hostname
      echo "Adding MACHINENAME [$(hostname -I)] to /etc/hosts"
      HOST_INFORMATION="$(hostname -I) MACHINENAME MACHINENAME.DOMAIN_LOWER"
      sed -i "/127.0.0.1/ a $HOST_INFORMATION" /etc/hosts
      cat /etc/hosts
      # Set timezone
      echo "Setting timezone"
      timedatectl set-timezone Europe/London
      # Create a default sssd.conf file
      echo "Creating sssd config"
      cp /usr/share/doc/sssd-common/examples/sssd-example.conf /etc/sssd/sssd.conf
      cat /etc/sssd/sssd.conf
      # Edit LDAP config
      echo "Creating LDAP config"
      mv /ldap.conf /etc/ldap.conf
      cat /etc/ldap.conf
      # Store LDAP secret
      echo "Storing LDAP secret"
      echo "LDAP_SECRET_PLAINTEXT" > /etc/ldap.secret
      chmod 0600 /etc/ldap.secret
      # Edit Kerberos config
      echo "Updating Kerberos config"
      mv /krb5.conf /etc/krb5.conf
      cat /etc/krb5.conf
  - path: "/active_directory_step02_realm_join"
    content: |
      # Join the VM to the domain
      echo "Joining VM to the domain"
      cat /etc/ldap.secret | realm join --verbose -U LDAP_USER DOMAIN_LOWER --install=/
  - path: "/active_directory_step03_update_sssd"
    content: |
      # Check the sssd.conf file
      echo "Updating sssd settings"
      sed -i -E 's/(use_fully_qualified_names = ).*/\1False/' /etc/sssd/sssd.conf
      sed -i -E 's|(fallback_homedir = ).*|\1/home/%u|' /etc/sssd/sssd.conf
      sed -i -E 's/(access_provider = ).*/\1simple/' /etc/sssd/sssd.conf
      cat /etc/sssd/sssd.conf
      # Restart the sssd daemon
      echo "Restarting sssd"
      systemctl restart sssd
  - path: "/active_directory_step04_update_pam"
    content: |
      # Edit the pam session configuration file
      echo "Updating PAM configuration"
      PAM_INFORMATION="session required|pam_mkhomedir.so|skel=/etc/skel/|umask=0022"
      sed "/pam_unix/ a $PAM_INFORMATION" /etc/pam.d/common-session | tr "|" "\t" > common-session
      mv common-session /etc/pam.d/common-session
      cat /etc/pam.d/common-session
  - path: "/etc/pip.conf"
    content: |
      # Add the PyPI mirror to our global settings
      [global]
      index = http://PYPI_MIRROR_IP:3128
      index-url = http://PYPI_MIRROR_IP:3128/simple
      trusted-host = PYPI_MIRROR_IP
  - path: "/Rprofile.site"
    content: |
      ## Add the CRAN mirror to our global settings
      local({
          r <- getOption("repos")
          r["CRAN"] <- "http://CRAN_MIRROR_IP"
          options(repos = r)
      })
  - path: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <channel name="xfce4-panel" version="1.0">
        <property name="configver" type="int" value="2"/>
        <property name="panels" type="array">
          <value type="int" value="1"/>
          <value type="int" value="2"/>
          <property name="panel-1" type="empty">
            <property name="position" type="string" value="p=6;x=0;y=0"/>
            <property name="length" type="uint" value="100"/>
            <property name="position-locked" type="bool" value="true"/>
            <property name="size" type="uint" value="30"/>
            <property name="plugin-ids" type="array">
              <value type="int" value="1"/>
              <value type="int" value="3"/>
              <value type="int" value="15"/>
              <value type="int" value="4"/>
              <value type="int" value="5"/>
              <value type="int" value="6"/>
              <value type="int" value="2"/>
            </property>
          </property>
          <property name="panel-2" type="empty">
            <property name="position" type="string" value="p=10;x=0;y=0"/>
            <property name="position-locked" type="bool" value="true"/>
            <property name="plugin-ids" type="array">
              <value type="int" value="10"/>
              <value type="int" value="12"/>
              <value type="int" value="9"/>
              <value type="int" value="8"/>
              <value type="int" value="16"/>
              <value type="int" value="17"/>
              <value type="int" value="18"/>
              <value type="int" value="19"/>
              <value type="int" value="20"/>
              <value type="int" value="13"/>
              <value type="int" value="7"/>
            </property>
          </property>
        </property>
        <property name="plugins" type="empty">
          <property name="plugin-1" type="string" value="applicationsmenu"/>
          <property name="plugin-2" type="string" value="actions"/>
          <property name="plugin-3" type="string" value="tasklist"/>
          <property name="plugin-15" type="string" value="separator">
            <property name="expand" type="bool" value="true"/>
            <property name="style" type="uint" value="0"/>
          </property>
          <property name="plugin-4" type="string" value="pager"/>
          <property name="plugin-5" type="string" value="clock"/>
          <property name="plugin-6" type="string" value="systray"/>
          <property name="plugin-7" type="string" value="showdesktop"/>
          <property name="plugin-8" type="string" value="separator"/>
          <property name="plugin-9" type="string" value="launcher">
            <property name="items" type="array">
              <value type="string" value="15602672011.desktop"/>
            </property>
          </property>
          <property name="plugin-10" type="string" value="launcher">
            <property name="items" type="array">
              <value type="string" value="15602672012.desktop"/>
            </property>
          </property>
          <property name="plugin-11" type="string" value="launcher">
            <property name="items" type="array">
              <value type="string" value="15602672013.desktop"/>
            </property>
          </property>
          <property name="plugin-12" type="string" value="launcher">
            <property name="items" type="array">
              <value type="string" value="15602672014.desktop"/>
            </property>
          </property>
          <property name="plugin-13" type="string" value="separator"/>
          <property name="plugin-16" type="string" value="launcher">
            <property name="items" type="array">
              <value type="string" value="15602591101.desktop"/>
            </property>
          </property>
          <property name="plugin-17" type="string" value="launcher">
            <property name="items" type="array">
              <value type="string" value="15602591342.desktop"/>
            </property>
          </property>
          <property name="plugin-18" type="string" value="launcher">
            <property name="items" type="array">
              <value type="string" value="15602591513.desktop"/>
            </property>
          </property>
          <property name="plugin-19" type="string" value="launcher">
            <property name="items" type="array">
              <value type="string" value="15602591664.desktop"/>
            </property>
          </property>
          <property name="plugin-20" type="string" value="launcher">
            <property name="items" type="array">
              <value type="string" value="15602591915.desktop"/>
            </property>
          </property>
        </property>
      </channel>
  # - path: "/etc/xdg/xfce4/panel/launcher-16/15602591101.desktop"
  #   content: |
  #     [Desktop Entry]
  #     Name=Atom
  #     Comment=A hackable text editor for the 21st Century.
  #     GenericName=Text Editor
  #     Exec=/opt/atom/atom %F
  #     Icon=atom
  #     Type=Application
  #     StartupNotify=true
  #     Categories=GNOME;GTK;Utility;TextEditor;Development
  #     MimeType=text/plain
  #     X-Desktop-File-Install-Version=0.23
  #     X-XFCE-Source=file:///usr/share/applications/atom.desktop


runcmd:
  # Setup panel icons
  - cp /usr/share/applications/exo-file-manager.desktop /etc/xdg/xfce4/panel/launcher-10/15573939452.desktop
  - cp /usr/share/applications/xfce4-appfinder.desktop /etc/xdg/xfce4/panel/launcher-12/15573939454.desktop
  - cp /usr/share/applications/atom.desktop /etc/xdg/xfce4/panel/launcher-16/15602591101.desktop
  - cp /usr/share/applications/code.desktop /etc/xdg/xfce4/panel/launcher-17/15602591342.desktop
  - cp /usr/share/applications/rstudio.desktop /etc/xdg/xfce4/panel/launcher-18/15602591513.desktop
  - cp /usr/share/applications/www.octave.org-octave.desktop /etc/xdg/xfce4/panel/launcher-19/15602591664.desktop
  - cp /usr/share/applications/firefox.desktop /etc/xdg/xfce4/panel/launcher-20/15602591915.desktop
  # ==========================================
  # *** BEGINNING OF DSG-SPECIFIC COMMANDS ***
  # *** END OF DSG-SPECIFIC COMMANDS ***
  # ==========================================
  # Move CRAN mirror config to appropriate locations
  - cp /Rprofile.site /etc/R/Rprofile.site
  - cp /Rprofile.site /anaconda/envs/py27/lib/R/etc/Rprofile.site
  - cp /Rprofile.site /anaconda/envs/py36/lib/R/etc/Rprofile.site
  - cp /Rprofile.site /anaconda/envs/py37/lib/R/etc/Rprofile.site
  # Create shared data folder and grant all users access
  - echo "Creating shared data folder"
  - sudo mkdir /data
  - sudo chmod go+rw /data
  # Make sure that sssd is running
  - echo "Restart sssd service"
  - service sssd restart
  # Set py36 as default environment when launching a new shell
  - echo "Add py36 conda environment setup to global bashrc"
  - echo "conda activate py36" >> /etc/bash.bashrc
  # Disable light-locker which can cause irritating error messages
  - echo "Disable screen lock"
  - echo "Hidden=true" >> /etc/xdg/autostart/light-locker.desktop
  # Set default session to xfce4
  - echo "Set default session to xfce4"
  - mv /startwm.sh /etc/xrdp/startwm.sh
  - chmod 0755 /etc/xrdp/startwm.sh
  - echo xfce4-session > ~USERNAME/.xsession
  # Set default terminal for xfce
  - echo "Set default xfce terminal"
  - sed -i -E 's/(TerminalEmulator=).*/\1xfce4-terminal/' /etc/xdg/xfce4/helpers.rc
  # Ensure that user owns their home directory
  - echo "Ensure that user owns their home directory"
  - chown -R USERNAME ~USERNAME
  # Restart xrdp to reflect changes made above
  - echo "Restart xrdp"
  - service xrdp restart
  # Add execute permission to the Active Directory set up scripts
  - sudo chmod +x /active_directory_step01_pre
  - sudo chmod +x /active_directory_step02_realm_join
  - sudo chmod +x /active_directory_step03_update_sssd
  - sudo chmod +x /active_directory_step04_update_pam
  # Run the Active Directory set up scripts
  - sudo /active_directory_step01_pre
  - sudo /active_directory_step02_realm_join
  - sudo /active_directory_step03_update_sssd
  - sudo /active_directory_step04_update_pam
  # Remove the Active Directory set up scripts (as these contain secrets and are world readable
  - sudo rm /active_directory_step01_pre
  - sudo rm /active_directory_step02_realm_join
  - sudo rm /active_directory_step03_update_sssd
  - sudo rm /active_directory_step04_update_pam
  # Shutdown so that we can tell when the job has finished by polling the VM state
  - shutdown -P now

