---

# ssh_hardening role variables
sftp_enabled: true
ssh_print_last_log: true
ssh_print_pam_motd: true

# fail2ban role variables
fail2ban_services:
  - name: sshd
    maxretry: 5
    bantime: 1h

# apt Packages arranged into groups
apt_packages_development:
  - git
  - tmux
  - python3-venv
  - python3.9
  - python3.9-venv
  - julia
  - build-essential
  - octave
  - jupyter
  - gfortran
  - r-base

apt_packages_shells:
  - bash
  - zsh
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - fish

apt_packages_editors:
  - vim
  - vim-fugitive
  - vim-syntastic
  - vim-julia
  - vim-airline
  - vim-airline-themes
  - vim-latexsuite
  - neovim
  - vim-gtk3
  - emacs

apt_packages_latex:
  - texlive-full
  - texstudio
